### PR TITLE
Docker configuration

### PR DESCRIPTION
**Pull request by jt196**
Hey @terrelsa13, I decided to get this set up in Docker as that's how I run Jellyfin. 

I've written some docs, there's a Dockerfile and full instructions on how to get it running. 

Hope this is of some help, no worries if you want to keep things simple though!

### CODE REVIEW

**Comment by terrelsa13** [comment]
@jt196 Much appreciated!
I am not familiar with Docker containers. So it's going to take me a little while to figure out the best way to include this. Be patient with me while I learn.

**Comment by terrelsa13** [comment]
I see you used the master branch. Do you foresee any issues with what you have done when I merge the [media_cleaner_2p0_beta](https://github.com/terrelsa13/media_cleaner/tree/media_cleaner_2p0_beta) branch into the master? Plan is to perform the beta merge at the beginning of June.

**Comment by jt196** [comment]
@terrelsa13 ech sorry Git is not my strong point, thought I was on the beta branch! Can't envisage  any big differences unless there's a change in the requirements in the new setup. It's just running Python in a small docker container. 

Hopefully the readme I've included should give you a good head start. Jellyfin does quite well running in a docker container. Just make sure you use the LinuxServer one and not their own. 

The test.py file doesn't really need to be there for the sake of helping folks out troubleshooting I chucked a simple test file to check the output. If you need any help just give me a shout.

At a certain point I'd have thought that using a premade config file could be a nice way to reduce the command line interactions. Potentially output via the docker console rather than the log file as well would help keep things simpler. Works ok as is though.

**Comment by xiNeRoar** [comment]
when will this get approved? docker is really convenient and important for non-techy users...

**Pull request closed without merging**
